### ISSUE TITLE
I'm getting the following error on my Rails App

### ISSUE THREAD

**Issue by marvindanig** [bokmann/font-awesome-rails#102]
Change detected to: app/assets/stylesheets/application.scss
      error app/assets/stylesheets/application.scss (Line 6: File to import not found or unreadable: font-awesome.
Load paths:
  ../projects/APPNAME (DEPRECATED)
 ../projectsAPP/app/assets/stylesheets)

My Gemfile for assets looks something like this:

  gem 'haml-rails' 
  gem 'jquery-rails', '~> 2.1.1' 
  gem 'modernizr-rails' 
# Static Assets

  gem 'sass-rails', '~> 4.0.0' 
  gem 'jquery-rails', '~> 2.1.1' 
  gem 'autoprefixer-rails'
  gem 'font-awesome-rails' 

In the application.scss file I've added the following line, restarted multiple times:

@import "font-awesome";

What am I missing?

**Comment by wenweih** [comment]
Just restart your app,it work for me.
