### ISSUE TITLE
New 4.3 icons missing in 4.3.0.0?

### ISSUE THREAD

**Issue by jasper502** [bokmann/font-awesome-rails#127]
Just updated to 4.3.0.0 and none of the new icons are loading manually or via the helpers.  The pre-4.3 icons work fine.

Installed and updated the gem and restarted the development server - I could be missing something but not sure what.

**Comment by rmm5t** [comment]
This is a common report with every new release, and I'd really like to
understand the most common reason.

Please read all the debugging steps in the contribution guidelines and let
me know which one does the trick:

https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md

It's likely a caching issue with Sass or the asset pipeline or static
assets sitting in public/assets or another asset gem providing an old
version of the fonts.

**Comment by jasper502** [comment]
Thanks for the tip - it was a browser cache issue.  Opened in another browser to confirm.
