### ISSUE TITLE
New icons doesn't work

### ISSUE THREAD

**Issue by woohoou** [bokmann/font-awesome-rails#133]
I tried to use cart-plus or cart-arrow-down according with font awesome 4.3, but it doesn't show, I'm using font-awesome-rails 4.3.0.0.

**Comment by rmm5t** [comment]
@woohoou Please follow the debugging steps in the [contribution guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md) first. 

It's pretty unlikely that there's a problem with this gem. For example, I just rendered these from a Rails project running font-awesome-rails 4.3.0.0:

![carts](https://cloud.githubusercontent.com/assets/740/6242490/27721864-b6ed-11e4-8034-39bd056ce05b.png)
