### ISSUE TITLE
undefined method `fa_icon' 

### ISSUE THREAD

**Issue by prashantjois** [bokmann/font-awesome-rails#136]
I'm trying to use the helpers to generate links in this manner:

```ruby
link_to fa_icon("sign-in", text: "Login"), login_path
```

but I'm getting the  exception

```ruby
undefined method `fa_icon' for #<#<Class:0x007f725cededd0>:0x007f725dcbfbe8>
```

Is there something special I need to do to get the helpers installed?

**Comment by rmm5t** [comment]
Please read the debugging steps in the [contribution guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md) first.

1. What version of Rails?
1. Did you remember to run `bundle install` and restart your dev server?
1. Is `gem "font-awesome-rails"` incorrectly sitting in the `:assets` group of your Gemfile or similar?  Make sure it's out in the main group of your Gemfile, so your development env can pick it up.

**Comment by prashantjois** [comment]
@rmm5t Thanks for the quick reply.

* rails 4.2.0
* Yes, I've restarted many times, and the library works otherwise (I can use "fa" classes manually just fine).
* Gem is in the main group

**Comment by prashantjois** [comment]
For now I've had to fake it out by adding my own helper to `application_helper.rb`

```ruby
  def fa_icon icon_name, text
    content_tag(:i, text, class: "fa fa-#{icon_name}")
  end 
```

**Comment by rmm5t** [comment]
> For now I've had to fake it out by adding my own helper to application_helper.rb

If you need to do that, you definitely have something wrong with your general rails setup or Gemfile.

Read the contribution guidelines. Just because you can use a `fa` icon manually doesn't mean that you have font-awesome-rails configured correctly. You may very well also have another gem loaded that also includes FontAwesome font assets (a common mistake).

**Comment by onebree** [comment]
@prashantjois using Haml, I have accomplished what you are trying, with the following snippet.

```haml
= link_to "#{fa_icon("sign-in")} Login".html_safe, login_path
```

**Comment by rmm5t** [comment]
@onebree Slightly cleaner would be:

```haml
= link_to fa_icon("sign-in", text: "Login"), login_path
```

**Comment by DownUndered** [comment]
My version 
<%= link_to login_path do %>
  <%= icon('far', 'sign-in', text: 'Login') %>
<% end %>
