### ISSUE TITLE
Icons does not work, shows boxes instead

### ISSUE THREAD

**Issue by rakeshostwal** [bokmann/font-awesome-rails#139]
I installed font-awesome-rails gem and trying to use icons for `li` and `arrows` but instead of icon i am getting just boxes on the UI. 
I did installed and added `= require font-awesome` in my css file.
Do I need to do something extra.

**Comment by rmm5t** [comment]
When you submitted this Issue, GitHub prompted you to **first read our [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md)**.  We'd really appreciate it if you could do that first.

These guidelines provide good debugging steps that you should follow (often in general) before submitting an Issue here.

If you still have trouble after following all the steps, we can only help if you also submit the required bits of information that we ask for in those debugging steps.  Furthermore though, GitHub Issues are better for true bug reports and/or feature requests. Researching our existing closed Issues and/or [StackOverflow](http://stackoverflow.com/) is often a better tool for general help in scenarios like this.

I'm closing this issue, but feel free to submit more information and request that we re-open it if you feel that is warranted later.
