### ISSUE TITLE
Some fonts icons are not show up 

### ISSUE THREAD

**Issue by anuradhaBissa** [bokmann/font-awesome-rails#145]
I am trying to use the "car" and "cart-arrow-down" icon in my website. I used some others like plane and facebook and they worked.

**Comment by rmm5t** [comment]
Here's the result of a sanity-test from Rails 4.2 and font-awesome-rails 4.3:

<img width="202" alt="fa" src="https://cloud.githubusercontent.com/assets/740/8752881/8c88de16-2c74-11e5-92a1-7e6b071469a5.png">

When you submitted this Issue, GitHub prompted you to **first read our [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md)**.  We'd really appreciate it if you could do that first.

These guidelines provide good debugging steps that you should follow (often in general) before submitting an Issue here.

If you still have trouble after following all the steps, we can only help if you also submit the required bits of information that we ask for in those debugging steps.  Furthermore though, GitHub Issues are better for true bug reports and/or feature requests. Researching our existing closed Issues and/or [StackOverflow](http://stackoverflow.com/) is often a better tool for general help in scenarios like this.

I'm closing this issue, but feel free to submit more information and request that we re-open it if you feel that is warranted later.
