### ISSUE TITLE
NoMethodError - `undefined method `fa_icon'`

### ISSUE THREAD

**Issue by AdamDenoon** [bokmann/font-awesome-rails#148]
I'm getting the following when trying to use fa_icon('edit'):

    undefined method `fa_icon' for #<#<Class:0x007f4a7a52b2e8>:0x007f4a79c61cc0>

Here is my .html.erb usage:

    <%= link_to edit_frame_path(frame), :class=>"btn-edit" do %>
        <%= fa_icon('edit') %>
    <% end %>

Here is the output of ` bundle list | grep '\(rails\)\|\(awesome\)'`:

    * coffee-rails (4.1.0)
    * font-awesome-rails (4.4.0.0)
    * jquery-rails (4.0.4)
    * rails (4.2.3)
    * rails-deprecated_sanitizer (1.0.3)
    * rails-dom-testing (1.0.6)
    * rails-html-sanitizer (1.0.2)
    * sass-rails (5.0.3)
    * sprockets-rails (2.3.2)

My setup:

  `ruby -v` : `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`
  `rails -v` : `Rails 4.2.3`
  * (Environment : Development)

My application.css file:

    /*
    *= require_tree .
    *= require_self
    */
 
    /*
    *= require font-awesome
    */

**Comment by rmm5t** [comment]
@AdamDenoon Thank you for reading the contribution guidelines before submitting an issue!

Is `fon

**Comment by rmm5t** [comment]
@AdamDenoon Thank you for reading the contribution guidelines before submitting an issue!

Is `font_awesome_rails` in the default group of your Gemfile or specified in some other group of your Gemfile? I.e. Is font_awesome_rails getting automatically loaded in your development env?

Sanity check: Are you sure your development server was restarted after updating your Gemfile?

**Comment by AdamDenoon** [comment]
Sanity check warranted: I had reloaded via `rails console` ... `reload!` (I'm using Apache + Passenger), but had to restart Apache. A `sudo service apache2 restart` fixed my problem. Thanks!

**Comment by rmm5t** [comment]
Glad to here it.
