### ISSUE TITLE
font-awesome-rails and jquery-awesome-cursor

### ISSUE THREAD

**Issue by DannyBen** [bokmann/font-awesome-rails#151]
This is a cross-project issue, so not sure it is the *perfect* place for this ticket, but I guess it's at least 50% ok... :)

I am trying to use [jquery-awesome-cursor](https://github.com/jwarby/jquery-awesome-cursor) which, as the name suggests, provides a way to use Font Awesome as a cursor.

With font-awesome-rails, the icons are not loading. I have opened a [detailed ticket](https://github.com/jwarby/jquery-awesome-cursor/issues/18) over there, but the owner does not use rails, so can't help figuring out the problem.

**Comment by rmm5t** [comment]
Closing this out. Browsers can load fonts after `DOMContentLoaded` potentially causing a race condition with jquery-awesome-cursor. Either jquery-awesome-cursor should take this into consideration internally, or they should update their docs to only load the plugin after fonts are finished loading.
