### ISSUE TITLE
assets:precompile fails

### ISSUE THREAD

**Issue by arinhouck** [bokmann/font-awesome-rails#157]
`Sass::SyntaxError: Undefined variable: "$fa-css-prefix".`
Someone on the sass gem is also experiencing same issue
(https://github.com/FortAwesome/font-awesome-sass/issues/107)

I have looked over the guidelines and also made my class is `application.css.scss`
It runs fine on locahost, but I can't deploy to heroku because assets:precompile fails.

**Comment by rmm5t** [comment]
This can't really have anything to do with this gem. As a design decision, we don't use sass here, and that (`$fa-css-prefix`) is a sass variable. 

This sounds like you have another gem trying to incorporate font awesome assets. Please read our [contribution guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md), specifically:

>  8\. Please make sure that **no other gem dependencies in your project also include outdated versions** of the FontAwesome fonts.

**Comment by montdidier** [comment]
@arinhouck I'm using font-awesome-rails and it works for me. My problem was with font-awesome-sass.
