### ISSUE TITLE
gem includes emacs lock file.

### ISSUE THREAD

**Issue by sugi** [bokmann/font-awesome-rails#158]
First, Thank you for your convenient gem!

I find font-awesome-rails-4.5.0.0.gem includes emacs lock file
'app/helpers/font_awesome/rails/#icon_helper.rb#' in the archive.

```
sugi@tempest:~/lib/rubygems/2.2/cache% tar vxf font-awesome-rails-4.5.0.0.gem --exclude metadata.gz --exclude checksums.yaml.gz -O | tar tz   
data.tar.gz
LICENSE
README.md
Rakefile
app/assets/fonts/FontAwesome.otf
app/assets/fonts/fontawesome-webfont.eot
app/assets/fonts/fontawesome-webfont.svg
app/assets/fonts/fontawesome-webfont.ttf
app/assets/fonts/fontawesome-webfont.woff
app/assets/fonts/fontawesome-webfont.woff2
app/assets/stylesheets/font-awesome.css.erb
app/helpers/font_awesome/rails/#icon_helper.rb#        <==  here
app/helpers/font_awesome/rails/icon_helper.rb
lib/font-awesome-rails.rb
lib/font-awesome-rails/engine.rb
lib/font-awesome-rails/version.rb
test/dummy/app/assets/stylesheets/sass-import.css.sass
test/dummy/app/assets/stylesheets/scss-import.css.scss
test/dummy/app/assets/stylesheets/sprockets-require.css
test/dummy/app/controllers/pages_controller.rb
test/dummy/app/views/pages/icons.html.erb
test/dummy/config.ru
test/dummy/config/application.rb
test/dummy/config/boot.rb
test/dummy/config/environment.rb
test/dummy/config/initializers/secret_token.rb
test/dummy/config/routes.rb
test/dummy/log/test.log
test/font_awesome_rails_test.rb
test/icon_helper_test.rb
test/test_helper.rb
```

**Comment by rmm5t** [comment]
Yes, you're correct. Sorry about that. That looks like it was accidentally included from my development environment when I built the gem. 

I don't plan on releasing a new version of the gem to fix this unless it's causing a problem that I'm not able to envision. However, we can probably take steps to prevent this kind of mistake in the future.  I've never been a fan of relying on the semi-standard approach of using `git ls-files` in the gemspec for building the manifest, but it might just be the cleanest approach..

**Comment by rmm5t** [comment]
Thanks again for this bug report. It should be fixed in the next release.
