### ISSUE TITLE
bootstrap template having something like this

### ISSUE THREAD

**Issue by Siplicity14** [bokmann/font-awesome-rails#161]
"fa-stack fa-4x"
im using a bootstrap template,i dont know what the above means, but it shows an icon or glyficon, of which i want to change, and put my own
what can i do?
thats in the "span class.." 
im new here dont know it goes,

**Comment by rmm5t** [comment]
@Siplicity14 Perhaps, you'll find value in reading the Examples page for Font Awesome:
https://fortawesome.github.io/Font-Awesome/examples/

This gem is just a wrapper around the core icon library for Rails supportl

**Comment by rmm5t** [comment]
Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.
