### ISSUE TITLE
Only the "web application icons" group works in Safari.

### ISSUE THREAD

**Issue by ddeyoung** [bokmann/font-awesome-rails#163]
All browsers display additional icon groups, but not Safari. I've tried all the contribute guideline steps with no improvements. Using the font from the bootstrap CDN resolves the issue. I'm using the latest version of the gem that includes Font Awesome 4.5.0 and I'm also using the same version from the CDN to debug.

Attempting to use `content: "\f201"` (line-chart) results in blank content and not a "missing icon box" like you'd expect. This same icon works in other browsers (Chrome & Firefox), just not safari. Replacing the content with `content: "\f071"` (exclamation-triangle) results in the proper icon being included.

I'm using the unicode characters in this example because that's the technique I'm using in my app, but the class technique has the same issue in Safari.

**Comment by rmm5t** [comment]
Are you sure you read _"all the contribution guideline steps"_?  Looks like Step 10 is missing here.

I cannot help here without more information, aside from telling you that the problem you're experiencing is unlikely to be related to this gem. My guess is that the assets from this gem aren't getting included correctly, or there's another gem competing for the same asset resource path.

**Comment by ddeyoung** [comment]
Swapped out with the official font-awesome-sass gem and all is in working order.
