### ISSUE TITLE
Scale Text with Icon in fa_icon helper

### ISSUE THREAD

**Issue by nacengineer** [bokmann/font-awesome-rails#164]
Its a bit of a visual bug to add 2x to an icon via the fa_icon helper and not have the text inherit the fa-2x class too. 

![Example of Visual Appearance](https://www.dropbox.com/s/5p4a1db69a9phwa/Screenshot%202016-03-11%2010.44.22.png?dl=1)

Wouldn't it be more proper to scale the text to the same size as the icon as this is the most likely desired behavior

![proposed alternate](https://www.dropbox.com/s/37ut4pu1aijq6h3/Screenshot%202016-03-11%2010.44.39.png?dl=1) 

 
This could be done via moving the fa-2x to a wrapper span. 

```html
<span class='fa-2x'>
  <i class="fa fa-file-pdf-o"></i>
  Some text here
</span>
```

**Comment by rmm5t** [comment]
Hmm. Interesting edge case, but I don't think we should do anything about this. 

1. `fa-2x` isn't meant to be used outside an individual icon. i.e. It is intended to always be combined with another `fa` class.
2. Related, wrapping any kind of readable text with a `fa` prefixed class is not how Font-Awesome was designed to be used.
3. Our `:text` option on the `fa_icon` is just a quick ease-of-use facilitating option. The text is not given any kind of wrapper, and we don't currently intend to give it a wrapper. If you want the text to have other behavior, don't use the `:text` option, or wrap the entire `fa_icon` call with something else. Reasons were covered in #114 and #135.

For example, even though it violates what I believe to be Font-Awesome's intent, you can achieve your desired behavior with this:

**HAML**

```haml
%span.fa-2x= fa_icon "file-pdf-o", text: file.name
```

**ERB**

```erb
<span class="fa-2x"><%= fa_icon "file-pdf-o", text: file.name %></span>

**Comment by nacengineer** [comment]
Your choice to not do it though as I can (and do) fall back to just rolling my own or use your solution. I was just suggesting this as fa_icon kind of falls into a decorator pattern so you could roll this up into it. Your call though.  Overall I can't complain about the awesomeness of your gem. Well documented and kept up-to-date swimmingly well. Keep up the good work.

**Comment by rmm5t** [comment]
Thanks for understanding. With 4M total downloads of this gem (which probably equates to thousands of active projects using it), making a change like the one proposed here becomes quite a bit of a backwards compatibility nightmare. I just don't think the cost outweighs the reward.
