### ISSUE TITLE
require 'pry' in railtie.rb

### ISSUE THREAD

**Issue by ijdickinson** [bokmann/font-awesome-rails#165]
I installed `font-awesome-rails` using Bundler, and then my rails server failed to start because it couldn't require pry (I've switched to byebug, so pry isn't a dependency in my project). Investigating, I found:

    ian@ian-desktop $ gem install fontawesome-rails
    Successfully installed fontawesome-rails-4.0.3.0
    Parsing documentation for fontawesome-rails-4.0.3.0
    Installing ri documentation for fontawesome-rails-4.0.3.0
    Done installing documentation for fontawesome-rails after 0 seconds
    1 gem installed

    ian@ian-desktop $ gem which -a fontawesome/rails/railtie.rb
    /home/ian/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fontawesome-rails-4.0.3.0/lib/fontawesome/rails/railtie.rb

    ian@ian-desktop $ gem which -a fontawesome/rails/railtie.rb | xargs cat
    require 'pry'
    module Fontawesome
      module Rails
        class Railtie < ::Rails::Railtie
          config.assets.paths << File.join(File.dirname(__FILE__), '..', '..', '..', 'vendor', 'assets', 'fonts').to_s

          config.assets.precompile += %w( .eot .woff .ttf)
        end
      end
    end

If pry is actually required here, it should be a dependency in the `Gemfile`, but I suspect this is accidentally left over from some debugging session.

**Comment by ijdickinson** [comment]
Sorry, confusion between `fontawesome-rails` and `font-awesome-rails`. Not your problem!

**Comment by rmm5t** [comment]
@ijdickinson Thanks for following-up, explaining the confusion, and closing this out. That other gem doesn't look like it's maintained anymore. You might want to consider switching.

**Comment by ijdickinson** [comment]
@rmm5t I already switched, the instant I realised what was going on. So far, `font-awesome-rails` has been rock solid. Go hyphens! :)
