### ISSUE TITLE
gem install font-awesome-rails -v '4.5.0.1' fails

### ISSUE THREAD

**Issue by IslamAzab** [bokmann/font-awesome-rails#166]
> ERROR:  Error installing font-awesome-rails:
>    invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) /<path_to_gem>/font-awesome-rails-4.5.0.1.gem

**Comment by rmm5t** [comment]
This is likely a result from a broken connection while downloading from RubyGems. Please clean out your rubygems cache within your ruby installation and try the `gem install` again.
