### ISSUE TITLE
Missing Icons on IE 11

### ISSUE THREAD

**Issue by ticktricktrack** [bokmann/font-awesome-rails#167]
When importing Font Awesome via the gem, I'm missing a whole bunch of icons, see screenshot. However, when I import without the gem , via copying the `scss` into assets and the fonts into `public/fonts` all the items show up fine.

```
//without gem
// Load font awesome 4.5
$fa-font-path: "../../fonts/font-awesome";
@import "../../../vendor/assets/stylesheets/font-awesome/font-awesome";
```

![screen shot 2016-03-30 at 15 16 31](https://cloud.githubusercontent.com/assets/82336/14147985/9ea22dd2-f695-11e5-8e3f-d268c8265ab8.png)

**Comment by alexmarles** [comment]
Hi, I have missing icons too but am experiencing this issue in **Chrome** (49.0.2623.110), **Firefox** (44.0.2) and **Opera** (36.0.2130.46), all of them using Mac OS X 10.11.4. The only browser in my computer that is showing all of them is Safari, but in other devices, as an iPad (using Safari), the icons don't show.

I haven't tried all of the icons, but the one I can't see is a very significant one: **fa-check**. Others, like fa-times or fa-gear, are shown correctly.

I am using **Rails 3.2.22.2** and SCSS files, I have updated the font-awesome-rails gem to the latest version (**4.5.0.1**) and everything is running on **Ruby 2.1.1**.

One thing I tried is to change ```:before``` to ```::before``` (notice the double colon) in the gem source code for this specific class and it works. This could be an issue with newer versions of the browsers, as the first option is outdated according to [Mozilla Developer Network docs](https://developer.mozilla.org/en-US/docs/Web/CSS/::before), but it doesn't explain why some icons are shown and others not.

The link to the Contribution Guidelines that @rmm5t posted is broken, but I think I have the other two points covered.

**Comment by ticktricktrack** [comment]
@rmm5t We do have an old version of https://github.com/seyhunak/twitter-bootstrap-rails in the project. I'll check if that offers a very outdated `.eot` file.

**Comment by rmm5t** [comment]
> The link to the Contribution Guidelines that @rmm5t posted is broken

Whoops. Sorry. It was moved. Here you go: 
https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md

**Comment by rmm5t** [comment]
> @rmm5t We do have an old version of https://github.com/seyhunak/twitter-bootstrap-rails in the project. I'll check if that offers a very outdated .eot file. Do you know if the file itself would contain version metadata?

Guarantee that's the problem. If you have a version of that gem and it still contains fontawesome, you have a version that's almost 2 years old. They didn't maintain things very well back then, and they dropped fontawesome bundling in favor of our gem.  I highly recommend bootstrap-sass gem if you need to keep older bootstrap assets and don't want fontawesome conflicts.

**Comment by ticktricktrack** [comment]
@rmm5t An upgrade to the new bootstrap is planned, but it's such a vital part of our app, I'm do fear meddling with that. From my side you can close this one. Not sure about @alexmarles issue though

**Comment by alexmarles** [comment]
In my case I don't have or had this gem installed, so it might be something else. I'll open a new issue to discuss it and I will search for some gem in my project that can be interfering...
