### ISSUE TITLE
Missing fa-check icon on some browsers

### ISSUE THREAD

**Issue by alexmarles** [bokmann/font-awesome-rails#168]
As I said in issue #167 that ended up not being related with this one:

> I am experiencing this issue in **Chrome** (49.0.2623.110), **Firefox** (44.0.2) and **Opera** (36.0.2130.46), all of them using Mac OS X 10.11.4. The only browser in my computer that is showing all of them is Safari, but in other devices, as an iPad (using Safari), the icons don't show.
> 
> I haven't tried all of the icons, but the one I can't see is a very significant one: **fa-check**. Others, like fa-times or fa-gear, are shown correctly.
> 
> I am using **Rails 3.2.22.2** and SCSS files, I have updated the font-awesome-rails gem to the latest version (**4.5.0.1**) and everything is running on **Ruby 2.1.1**.
> 
> One thing I tried is to change ```:before``` to ```::before``` (notice the double colon) in the gem source code for this specific class and it works. This could be an issue with newer versions of the browsers, as the first option is outdated according to [Mozilla Developer Network docs](https://developer.mozilla.org/en-US/docs/Web/CSS/::before), but it doesn't explain why some icons are shown and others not.

- [x] Yes, I have tried all 10 debugging steps outlined in the [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md).

This is ```bundle list | grep 'rails\|awesome\|sass\|less'``` my output:
```
  * apipie-rails (0.2.6)
  * awesome_print (1.6.1)
  * bootstrap-sass (3.1.1.1)
  * carmen-rails (1.0.1)
  * coffee-rails (3.2.2)
  * compass-rails (2.0.0)
  * cucumber-rails (1.4.3)
  * elasticsearch-rails (0.1.8)
  * facebox-rails (0.2.0)
  * factory_girl_rails (4.6.0)
  * font-awesome-rails (4.5.0.1)
  * intercom-rails (0.2.30)
  * jquery-rails (3.1.4)
  * jquery-ui-rails (5.0.3)
  * premailer-rails (1.9.0)
  * rails (3.2.22.2)
  * rails-i18n (3.0.1)
  * redis-rails (3.2.4)
  * rspec-rails (2.13.2)
  * sass (3.4.21)
  * sass-rails (3.2.6)
  * slim-rails (1.1.1)
```

Using web inspector in all others icons that are shown and the fa-check that is shown using Safari, all seem to be affected only by font-awesome-rails rules and not overridden by any other rule. When I try to see if anything is overriding the content rule for the fa-check element, it doesn't show any content for the ```:before``` pseudo-element. If I add the same rule in my SCSS file that FA adds for the .fa-check class, the icon is visible. So I have a workaround, but I can't be doing this for every icon that doesn't shows...

Any help or tip is welcome. Thanks.

**Comment by rmm5t** [comment]
@alexmarles Thank you for the clean report. 

I don't immediately see any problems with what you've shared here. However, I'm 99% certain the problem either isn't related to this project or there's still a potential caching issue.  Have you tried `rake tmp:cache:clear` combined with a dev server restart?

**Comment by rmm5t** [comment]
> When I try to see if anything is overriding the content rule for the fa-check element, it doesn't show any content for the :before pseudo-element.

Weird. 

Have you checked the actual HTTP response body on your CSS file? `.fa-check:before` is clearly defined by this gem: https://github.com/bokmann/font-awesome-rails/blob/master/app/assets/stylesheets/font-awesome.css.erb#L225-L227

Are you sure you have the proper CSS _require/import_ for your specific CSS templating language? Per our [Usage instructions](https://github.com/bokmann/font-awesome-rails#usage)?

**Comment by alexmarles** [comment]
Hi @rmm5t,

I have found where the error was. You were right saying the problem wasn't related to this gem. It was an other scss file extending .fa-check class to an other class. I really don't understand why this was interfering with it because that line it's been there for months and the problem was noticed only a few days ago...

Still, thanks for your help. You can close this issue now.

**Comment by rmm5t** [comment]
Thanks for following up with this!
