### ISSUE TITLE
Skinnier  FontAwesome assets

### ISSUE THREAD

**Issue by Janther** [bokmann/font-awesome-rails#171]
Is there a plan to add an icon-picker feature in order to have smaller fonts and css?
I imagine a `config/fa.yml` file or initializer listing only the icons used in the application. And only these icons will be included in the resulting `css` and `fonts` in the precompile process.

**Comment by rmm5t** [comment]
Sorry. No plans for that. Also, considering the entire font library asset is smaller than most header logos images and the assets are cached in the browser after the first download, I really don't see much of a benefit for the additional complexity.
