### ISSUE TITLE
fa_icon is undefined for views when running specs

### ISSUE THREAD

**Issue by crawfoal** [bokmann/font-awesome-rails#173]
[X] Yes, I have tried all 10 debugging steps outlined in the [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md).

I have been using font-awesome-rails for a while with no issues, however after installing the ammeter gem (helps in writing specs for rails generators, so shouldn't be related to FontAwesome...), I started having issues with the `fa_icon` being undefined when called from views when running specs *only* (everything works fine in development and production). I have submitted an issue to them, but I'm starting to wondering if this is either an issue with font-awesome-rails only, or a combination of the two, or possibly an issue rspec-rails and how they include helper methods in the `view` and `helper` objects of the respective spec types.

I saw that this gem has had quite a few issue submitted regarding `fa_icon` being undefined, so I'm hoping that you'll be able to point us in the right direction. A few notes:
- I've `bundle install`'d and restarted the server and such.
- As far as I can tell, I don't have any other gems that use FontAwesome.
- font-awesome-rails is not in my assets group
- Here is the output of the `bundle list` command:
  * awesome_print (1.6.1)
  * coffee-rails (4.1.1)
  * factory_girl_rails (4.7.0)
  * font-awesome-rails (4.6.1.0)
  * haml-rails (0.9.0)
  * jquery-rails (4.1.1)
  * rails (4.2.6)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-erd (1.4.7)
  * rails-html-sanitizer (1.0.3)
  * rails_12factor (0.0.3)
  * rails_serve_static_assets (0.0.5)
  * rails_stdout_logging (0.0.5)
  * rspec-rails (3.4.2)
  * sass (3.4.22)
  * sass-rails (5.0.4)
  * sprockets-rails (3.0.4)

I made a copy of the project I'm working on, which you can find here: https://github.com/crawfoal/metanoia-view-helper-issues. The README gives more details about the issues I'm seeing.

The issue I created for the ammeter gem is here: https://github.com/alexrothenberg/ammeter/issues/53

**Comment by rmm5t** [comment]
I'm not an rspec advocate (in fact, I'm the complete opposite), and I'm not an advocate of "view specs"; however, it looks like you're fighting a limitation of rspec-rails. I don't know how this relates to ammeter (I didn’t play with that permutation).

I submitted you a PR that helps remedy the test suite of your project to behave as you would expect.
https://github.com/crawfoal/metanoia-view-helper-issues/pull/1

1. Including `FontAwesome::Rails::IconHelper` in your `ApplicationHelper` should never be necessary.
2. You must declare which helpers you want to include when you run view specs using rspec-rails.  Why? I have no earthly idea, but rspec-rails documents this.
