### ISSUE TITLE
Icons are not showing up in IE 11

### ISSUE THREAD

**Issue by krinkere** [bokmann/font-awesome-rails#177]
tried all the steps in troubleshooting guide and here is the output of bundle list| grep \rails, etc..

  * autoprefixer-rails (6.4.0.1)
  * bootstrap-sass (3.3.7)
  * coffee-rails (4.1.1)
  * factory_girl_rails (4.7.0)
  * font-awesome-rails (4.6.3.1)
  * jquery-rails (4.1.1)
  * rails (4.2.1)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.3)
  * rspec-rails (3.2.3)
  * sass (3.4.22)
  * sass-rails (5.0.6)
  * sprockets-rails (3.1.1)

Works just fine in Chrome and Firefox. Does not show up in IE 10.

Tried to insert 
  <meta http-equiv="cache-control" content="max-age=0" />
  <meta http-equiv="cache-control" content="no-cache" />
  <meta http-equiv="expires" content="0" />
  <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
  <meta http-equiv="pragma" content="no-cache" />

still no luck

**Comment by krinkere** [comment]
Ummm... might not be my code since i just opened Font Awesome home page in IE and I can't see icons there too. phew

**Comment by rmm5t** [comment]
>  i just opened Font Awesome home page in IE and I can't see icons there too

Yeah, that sounds like a problem with your environment or IE or similar and/or Font Awesome core. Closing this issue out as it's unlikely related to this gem, but if you figure out the problem, feel free to post your findings here for posterity. It might help someone in the future.

**Comment by krinkere** [comment]
Yeah, it is not specific to the FontAwesome... Also tried bootstrap icons with the same result. Upon insvestigation I found this 
https://msdn.microsoft.com/en-us/library/ms533034(v=vs.85).aspx

Basically, I have group policy set on my workstation where IE has specific setting to restrict downloads. Wish I knew that few hours ago before exhausting my CSS wizardly
