### ISSUE TITLE
Rails 5 support for Font awesome v3

### ISSUE THREAD

**Issue by ronakjain90** [bokmann/font-awesome-rails#181]
Hello,

Would it be a good idea to maintain a separate `v3` branch? This branch would undertake any font awesome v3 updates if any. One possible update that I'm able to think of right now is to support rails 5. 

Let me know your thoughts, I'd be happy to submit a PR.

**Comment by rmm5t** [comment]
I'm inclined to say no considering that we don't have Rails 5 support for FA v4.0, v4.1, v4.2, or v4.4 either. It was first introduced to match with FA v4.5.

May I ask why you're still on FA v3 and haven't upgraded to FA v4.7?  Afterall, FA v3 is approaching 4 years old.

**Comment by ronakjain90** [comment]
It's more of a technical debt, we have to move on to rails-5 to utilize some of the newly introduced features.

Thankyou for your feedback, I'd add FA upgrade into our pipeline.
