### ISSUE TITLE
ActionView::Template::Error - File to import not found or unreadable: font-awesome.

### ISSUE THREAD

**Issue by francesco-loreti** [bokmann/font-awesome-rails#186]
Rails 5.1
version 4.7.0.2
Windows x64bit
application.sass
`@import font-awesome`

Error:
`ActionView::Template::Error - File to import not found or unreadable: font-awesome.`

**Comment by francesco-loreti** [comment]
On Master branch not have this error

**Comment by francesco-loreti** [comment]
any news?

**Comment by rmm5t** [comment]
> any news?

Any more information? 

This issue did not comply with the GitHub [issue template](https://github.com/bokmann/font-awesome-rails/blob/master/.github/ISSUE_TEMPLATE.md) nor the [Contributing guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md):

**Comment by rmm5t** [comment]
> On Master branch not have this error

The current master branch and v4.7.0.2 _should_ be identical.

**Comment by francesco-loreti** [comment]
Solved! I have uninstalled and re-installed the gem and it work! Bah.... You can close. Thanks.

**Comment by rmm5t** [comment]
Great. Thanks for checking back in that you solved this on your end. My guess is it was a caching issue -- either assets related or perhaps `spring` related.

**Comment by light-flight** [comment]
I have the same problem on Rails 5.0.3. And it doesn't solve by reinstalling
