### ISSUE TITLE
Consider supporting fixed-width as a passed option

### ISSUE THREAD

**Issue by SaladFork** [bokmann/font-awesome-rails#187]
FontAwesome supports [fixed-width icons](http://fontawesome.io/examples/#fixed-width) which are useful when using icons in a list.

This can currently be done with the helper as per:
```ruby
fa_icon 'user', class: 'fa-fw'
# => <i class="fa fa-user fa-fw"></i>
```

It would be nicer if this was something that could be passed as per `text` and `right`:
```ruby
# some ideas...
fa_icon 'user', fixed: true
fa_icon 'user', width: :fixed

# => <i class="fa fa-user fa-fw"></i>
```

**Comment by rmm5t** [comment]
Try:

```ruby
fa_icon 'user fw'
```

or 

```ruby
fa_icon ['user', 'fw']
```

**Comment by rmm5t** [comment]
Note: This also works for any FontAwesome modifiers. Examples:

```ruby
fa_icon "quote-left 4x"
fa_icon "li check-square"
```

**Comment by SaladFork** [comment]
Oh awesome, thank you!
