### ISSUE TITLE
README.md suggestion

### ISSUE THREAD

**Issue by hectorcorrea** [bokmann/font-awesome-rails#189]
In the section [Deploying to subfolders](https://github.com/bokmann/font-awesome-rails#deploying-to-sub-folders) of the README.md I would suggest a note indicating that it might be necessary to specify the `RAILS_RELATIVE_URL_ROOT` when **precompiling** the assets as indicated on [this link](https://github.com/bokmann/font-awesome-rails/issues/74#issuecomment-31359449) to deal with issues in which the fonts are picked up in a development machine but not on a development server.

**Comment by rmm5t** [comment]
PR welcome to reference this edge case in the readme.

**Comment by rmm5t** [comment]
Closed via #191
