### ISSUE TITLE
READ ME file

### ISSUE THREAD

**Issue by DenisLP** [bokmann/font-awesome-rails#196]
Hi, its my first contribution on this project.

While I was creating my rails app, when I try to add the font-awesome on my application.scss, the code on read me was:
`@import "font-awesome";`
And I got a error. But when I change to:
`@import "font-awesome.css";`
Worked fine.

I am not sure if I am doing something wrong adding this library on my project, or was a typo.

Thank you.

**Comment by rmm5t** [comment]
Hi @DenisLP, Sorry, I cannot reproduce. Spinning up a new rails application and depending on font-awesome-rails as defined in the README works as expected (assuming `sass-rails` is also installed).

Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.
