### ISSUE TITLE
Rails 5.2 support?

### ISSUE THREAD

**Issue by pwnious** [bokmann/font-awesome-rails#197]
Rails 5.2 support?

**Comment by brian-kephart** [comment]
I've been using the gem on Rails 5.2.0rc2 without issue. Probably just need to update the gemspec and make sure the tests don't fail.

**Comment by rmm5t** [comment]
I'll get a PR and a new release out shortly.

**Comment by rmm5t** [comment]
[v4.7.0.4 is in the wild](https://rubygems.org/gems/font-awesome-rails)
