### ISSUE TITLE
file-alt Missing Icon

### ISSUE THREAD

**Issue by derrickmar** [bokmann/font-awesome-rails#201]
I have tried all the steps in (https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md).

<%= fa_icon "file-alt" %> is missing.  <%= fa_icon "file" %> works however. Example: Notice how in the User Manual the file-alt icon is not being rendered

![screenshot 2018-08-11 11 00 15](https://user-images.githubusercontent.com/4853140/43994668-cc7c27e4-9d55-11e8-9708-54076dfdc13c.png)

bundle list | grep 'rails\|awesome\|sass\|less'
```
  * coffee-rails (4.2.2)
  * dotenv-rails (2.5.0)
  * font-awesome-rails (4.7.0.4)
  * rails (5.2.0)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.0.4)
  * sass (3.5.6)
  * sass-listen (4.0.0)
  * sass-rails (5.0.7)
  * sprockets-rails (3.2.1)
```

**Comment by rmm5t** [comment]
> I have tried all the steps in (https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md).

Thus is actually a clean issue report, but you missed step 2. 

> 2) Make sure the icon still exists in FontAwesome (sometimes icons are renamed between versions).

`file-alt` was renamed to `file-o`. 

https://fontawesome.com/v4.7.0/icons/

**Comment by derrickmar** [comment]
@rmm5t  thanks for the help. I thought we were on version 5, but just realized it's on 4.7. Is there any plans to upgrade? I was looking at these fonts

https://fontawesome.com/icons?d=gallery&q=file-alt

**Comment by derrickmar** [comment]
Gotcha. Appreciate it @rmm5t
