### ISSUE TITLE
Remove transitive dependency on sass gem

### ISSUE THREAD

**Issue by adjam** [bokmann/font-awesome-rails#203]
As of `v4.7.0.5`, this gem has a dependency on `sass-rails` which in turn depends on `sass`; the latter gem has been deprecated (http://sass.logdown.com/posts/7828841).

Probably the easiest change is to swap out the dependency in the gemspec for `sassc-rails`.

**Comment by rmm5t** [comment]
>  this gem has a dependency on sass-rails

Clarifying. Not exactly. It has a "development" dependency on sass-rails. This has no bearing on anyone's usage of the gem.

>  [sass] gem has been deprecated (http://sass.logdown.com/posts/7828841).

Good to know. Thanks.

> Probably the easiest change is to swap out the dependency in the gemspec for sassc-rails.

Please do investigate.  A PR ensuring the test suite still runs green using sassc-rails would be much appreciated.
