### ISSUE TITLE
Discord icon not working

### ISSUE THREAD

**Issue by tbhockey** [bokmann/font-awesome-rails#205]
```
> bundle list | grep 'rails\|awesome\|sass\|less'
  * coffee-rails (4.2.2)
  * factory_bot_rails (5.0.2)
  * font-awesome-rails (4.7.0.5)
  * jquery-rails (4.3.5)
  * js_cookie_rails (2.2.0)
  * rails (5.2.3)
  * rails-controller-testing (1.0.4)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.0.4)
  * rspec-rails (3.8.2)
  * sass (3.7.4)
  * sass-listen (4.0.0)
  * sass-rails (5.0.7)
  * sprockets-rails (3.2.1)
  * uploadcare-rails (1.2.1)
```

The discord icon (https://fontawesome.com/icons/discord?style=brands) specifically is not loading for me in Rails 5.

```
<%= fa_icon("discord") %>

# Generates
<i class="fa fa-discord"></i>
```

Fontawesome website suggests this should be `<i class="fab fa-discord"></i>`, but even if i do this manually I am still not getting any result.

**Comment by rmm5t** [comment]
font-awesome-rails is still tied to FontAwesome 4.7. The link you referenced is FontAwesome 5.x.

For FontAwesome 4.7 icons, see this:
https://fontawesome.com/v4.7.0/icons/

**Comment by tbhockey** [comment]
Ah, i thought that might be the case, but i was confused as many of the other logos im using said "5.0" and worked fine, so i wasn't sure. Thanks.

Any idea if you'll be moving to 5.X?
