### ISSUE TITLE
Rails 6.1 support

### ISSUE THREAD

**Issue by Vasfed** [bokmann/font-awesome-rails#206]
Rails master is `6.1.0-alpha` now, but current gemfile limits rails to `<6.1`.

Most probably this is just a question of relaxing version requirement.

**Comment by rmm5t** [comment]
I'll relax the gemfile in the master branch, but please note that there won't be an official gem release of font-awesome-rails until there's an official alpha or beta release of rails 6.1 published to rubygems.

**Comment by connorshea** [comment]
There's a rails 6.1.0.rc1 released on RubyGems now :)

**Comment by afomera** [comment]
Just to add to this, we've been running 6.1rc1/6.1rc2 in production and things have been working fine with the gem overall. Just need to bump the Gemspec so it will work with the official 6.1 release expected next week :)

**Comment by kvokka** [comment]
Rails 6.1 is out 🎉 

Can you please bump the gem version with the latest master?

**Comment by EnziinSystem** [comment]
Please upload to Rubygems.org.

Now, if I want to use Rails 6.1.0, I need to install this gem from github.

**Comment by morgoth** [comment]
@bokmann would it be possible to have a release with Rails 6.1 support?

**Comment by ShockwaveNN** [comment]
@rmm5t ping

**Comment by kvokka** [comment]
@rmm5t Can you please also publish gem to rubygems?
Thank you

**Comment by yevhene** [comment]
@rmm5t Please release it

**Comment by ShockwaveNN** [comment]
@rmm5t Any news on releasing gem to rubygems?
