### ISSUE TITLE
Icons appear as squares in production

### ISSUE THREAD

**Issue by ricsrock** [bokmann/font-awesome-rails#38]
Development looks great. On production server, icons appear as squares. I'm hoping it's something goofy that I'm missing.

After deployment, I run

bundle exec rake assets:precompile RAILS_ENV=production

on the production server. I can see that the helpers are calling for the fingerprinted application.css, and the fingerprinted font-awesome font files were generated, but the application.css is calling for un-fingerprinted font-awesome files... which are no where to be found.

Rails v4.0.0
font-awesome-rails v3.2.1.1

This app is being deployed to my own Mac OS X server 10.6 running apache and passenger (not sure that's relevant, but...)

Thanks for any help.

**Comment by charlesdg** [comment]
If you have a 404 error, try to add to `application.rb` or `production.rb` this line to precompile this kind of assets:

``` ruby
config.assets.precompile += ["*.ttf", "*.woff", "*.svg", "*.eot"] 
```

**Comment by morgler** [comment]
Did anyone ever solve this? It was gone for me for years, but now resurfaced after moving servers. It's strange that it only happens to the fonts (not to other assets) and it only fully fails in Firefox (though it reports errors in Chrome as well).

My setup:
- Rails 5.2 app
- font-aweseom-rails 4.7.0.5
- CDN is CloudFront
- Server: Hatchbox

Before the move to Hatchbox, it has worked for years on Heroku. I can remember that it took me months back then to finally kill this error – and I don't really know what of all the stuff actually (temporarily) fixed it then.
