### ISSUE TITLE
[request] Please make element (<i> vs <span>) optional for icon helpers

### ISSUE THREAD

**Issue by Undistraction** [bokmann/font-awesome-rails#62]
Bootstrap no longer uses `<i>` tags for icons (thank god). Please move helpers over to use `<span>` tags or allow choice between `<i>` and `<span>`.

From Bootstrap 3 Examples:

```
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-star"></span> Star
</button>
```

**Comment by dpanfili** [comment]
Another reason to change to <span> or other tag - using <i> is not ADA WCAG 2.0 compliant.
