### ISSUE TITLE
Some icons don't work

### ISSUE THREAD

**Issue by blarralde** [bokmann/font-awesome-rails#63]
I've set up the new version of font-awesome with the 'fa fa-<name>' classes and I get mixed results. While most icons work, some just don't display like 'fa fa-code'.
I see in the console that font-awesome.css is loaded, and the fa-code class gets matched. Same problem with fa-share-square and fa-thumbs-up. My guess is that the font itself is missing icons?

I updated to the last version of the gem (4.0.3.0 as of now). Could anybody tell me if I'm the only one getting this issue?

**Comment by jsimon727** [comment]
For some reason I can not get the 'user-plus' icon to work. All my other icons work as expected.

I have the most recent version of the font-awesome-rails gem and I'm using the following code:

<%= fa_icon("user-plus") %>

**Comment by rmm5t** [comment]
Did you follow the debugging steps in the contribution guidelines for this
project?

**Comment by jsimon727** [comment]
Got it to work, thank you! I thought I could bundle update without specifying a version, but I needed to put gem 'font-awesome-rails', '~> 4.3.0.0' and then bundle update.

**Comment by adibhise** [comment]
I have been trying some icons and they are not working. like i need this icon but not appearing <i class="fa fa-diamond"></i>

**Comment by rmm5t** [comment]
@adibhise This is a closed issue. 

> Diamond is not appearing.

Here's a screenshot from a Rails 4.2 app using the latest font-awesome-rails gem:
![rails4test 2015-08-12 11-42-32](https://cloud.githubusercontent.com/assets/740/9231774/3d3b4a74-40e7-11e5-9ab9-c97fc5b01cad.png)

**First read our [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md)**.  We'd really appreciate it if you could do that first.

These guidelines provide good debugging steps that you should follow (often in general) before submitting an Issue here.

If you still have trouble after following all the steps, we can only help if you also submit the required bits of information that we ask for in those debugging steps.  Furthermore though, GitHub Issues are better for true bug reports and/or feature requests. Researching our existing closed Issues and/or [StackOverflow](http://stackoverflow.com/) is often a better tool for general help in scenarios like this.

**Comment by arifhussain353** [comment]
With Aliases: ` <i class="fa fa-times-rectangle-o" aria-hidden="true"></i>`
Without Aliases: `<i class="fa fa-window-close-o" aria-hidden="true"></i>`
This icon is also not showing up with `Font Awesome 4.7.0`

**Comment by rmm5t** [comment]
@arifhussain353 Have you tried the debugging steps outlined in the [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/.github/CONTRIBUTING.md)?

Furthermore. This particular issue is closed, and the chances of getting help on a closed issue are thereby diminished. Also, if you try to submit a new issue, you'll be redirected to the debugging steps in the contribution guidelines.

We get "missing icon" claims on occasion, but there hasn't yet been a claim of missing icons that were actually missing. It's always been user-error, a misunderstanding of how Rails caching works, or conflict with another outdated font-awesome library. For example, here's a screenshot that I just took during a quick _sanity-check_ test from a Rails app that depends on **font-awesome-rails v4.7.0.1**:

![rails4test 2017-01-09 11-34-50](https://cloud.githubusercontent.com/assets/740/21778199/a916e898-d65f-11e6-9a18-ad1dcceb7cc9.png)
