### ISSUE TITLE
File to import not found or unreadable: font-awesome.

### ISSUE THREAD

**Issue by sambaptista** [bokmann/font-awesome-rails#73]
Hello, 

I'm beginning with rails bootstrap and font-awsome. I've installed font-awesome-rails as mentionned, but I don't understand one thing : Am I supposed to have source files somewhere ? 

My SCSS file contains : 

@import "compass_twitter_bootstrap";
@import "font-awesome";

So I suppose I should have a _font-awesome.scss in the same folder for the @import, but I've nothing and then when compass compiles my style.scss I get an error : File to import not found or unreadable: font-awesome. 

There is no _compass_twitter_bootstrap.scss neither but I don't get any error (except glyphicons-halflings.png not found). How does this work ? 

Bundle list :
- compass (0.12.2)
- compass_twitter_bootstrap (2.3.1)
- font-awesome-rails (4.0.3.0)
- more...

My Gemfile : 

gem 'compass_twitter_bootstrap'
gem 'font-awesome-rails'

Tthe bundle install returns this : 

Using rake (10.1.0) 
Using i18n (0.6.9) 
Using minitest (4.7.5) 
Using multi_json (1.8.2) 
Using atomic (1.1.14) 
Using thread_safe (0.1.3) 
Using tzinfo (0.3.38) 
Using activesupport (4.0.2) 
Using builder (3.1.4) 
Using erubis (2.7.0) 
Using rack (1.5.2) 
Using rack-test (0.6.2) 
Using actionpack (4.0.2) 
Using chunky_png (1.2.9) 
Using fssm (0.2.10) 
Using sass (3.2.12) 
Using compass (0.12.2) 
Using compass_twitter_bootstrap (2.3.1) 
Using thor (0.18.1) 
Using railties (4.0.2) 
Using font-awesome-rails (4.0.3.0) 
Using bundler (1.3.5) 

And the config.rb : 

http_path = "/"
css_dir = "wp-content/themes/rgs/css"
sass_dir = "wp-content/themes/rgs/css_sass"
images_dir = "wp-content/themes/rgs/deco"
javascripts_dir = "wp-content/themes/rgs/js"
cache_dir = "wp-content/themes/rgs/css_sass/cache"

Thx for your help.

**Comment by adityagamer786** [comment]
I restarted the server and everything worked
