### ISSUE TITLE
Rails 4, font-awesome not appearing in production environment

### ISSUE THREAD

**Issue by ijdickinson** [bokmann/font-awesome-rails#74]
My app is running just fine in development mode, but when I `cap deploy` to my production environment (EC2, as it happens, though I'm not sure how significant that is), the app can't resolve the font-awesome font. I'm using pretty much as-installed rails environment configurations, and Capistrano recipes. Everything else in the app runs just fine, it's only the font-awesome font that can't be found.

I'm at a bit of a loss to know how to debug this, so any suggestions gratefully received. Relevant extracts from my Gemfile: 

```
font-awesome-rails (4.0.3.0), 
rails (4.0.1)
```

Happy to provide any other details, but I don't which which ones are relevant and I don't want to waste folks' time by essentially posting the entire project!

**Comment by mooreniemi** [comment]
In my case had to do `rake assets:clean` then `RAILS_ENV=production bundle exec rake assets:precompile` and was all set. Just chiming in for posterity.

**Comment by Chrisgo-75** [comment]
I have never needed to do this before and all Rails apps are running on the same server. Following font-awesome-rails README "Deploying to sub-folders" section fixed the "404 Not Found fontawesome-webfont..." issues on production server. This is for a Rails 5.1.4 application.
