### ISSUE TITLE
Not Working on Heroku

### ISSUE THREAD

**Issue by SunnyIzr** [bokmann/font-awesome-rails#80]
Hey All:

I've been able to implement this locally with no problems at all, but for some reason when I push to heroku the symbols don't show up (they just show big square boxes). Furthermore, when I look at the console, I'm seeing 404 erros since none of the fontawesome fonts are found. Has anyone else had any luck with using this in Heroku production?

-Sunny

**Comment by elsurudo** [comment]
@SunnyIzr Can you detail those changes to help out others perhaps having the same problem?
