### ISSUE TITLE
Doesn't seem to work on Rails 4.1

### ISSUE THREAD

**Issue by arjan0307** [bokmann/font-awesome-rails#88]
I'm working on Rails 4.1, and the gem doesn't seem to work.

The helper functions are not available (`undefined_method`). And I can't load the stylesheet both with `require` in a manifest file and with `@import` in a `.scss` file.

Is Rails 4.1 unsupported?

**Comment by saddaaf** [comment]
very simple just put .scss.erb extention to awsome fonts in stylesheets toont-awesome.min.scss.erb and font-awesome.scss.erb

**Comment by felipeands** [comment]
I was have the same problem. Because I switch the branch without restart the server.
