### ISSUE TITLE
.fa-facebook .fa-twitter are not working

### ISSUE THREAD

**Issue by devilankur18** [bokmann/font-awesome-rails#96]
The icon for the .fa-facebook .fa-twitter are not showing up, where as its working for the others.

Check the cheatsheet here http://fortawesome.github.io/Font-Awesome/cheatsheet/. 

I think the wrong version of the font file is being used. Even the fontawesome homepage seems broken http://fortawesome.github.io/Font-Awesome/icons/

**Comment by herrjemand** [comment]
@devilankur18 OMFG. I thought I was going nuts. Bloody adblock. Thanks XD
